// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'animationDuration': string;
  'baseFontSize': string;
  'borderRadius': string;
  'boxShadow': string;
  'defaultThemeBackgroundColor': string;
  'defaultThemeForegroundColor': string;
  'defaultThemeMainColorDark': string;
  'defaultThemeMainColorLight': string;
  'defaultThemeMainColorRegular': string;
  'defaultThemeSecondaryColorDark': string;
  'defaultThemeSecondaryColorLight': string;
  'defaultThemeSecondaryColorRegular': string;
  'expandedTrendHeight': string;
  'gap': string;
  'halfPadding': string;
  'padding': string;
  'selectDropdownMaxHeight': string;
  'selectOptionHeight': string;
  'textFontFamiliy': string;
  'titleFontFamiliy': string;
  'trendHeight': string;
}
export const cssExports: CssExports;
export default cssExports;
